apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
spec:
  data:
    PORT: "8080"
    NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: web-secret
type: Opaque
stringData:
  DB_PASSWORD: "PasswordSeguro123"
